### ISSUE TITLE
process didn't exit successfully: `***Project***/target/debug/build/libfuzzy-sys-c071d6af6789541e/build-script-build` (exit status: 101)

### ISSUE THREAD

**Issue by Eclextic** [s3rvac/ssdeep-rs#3]
System Information: Linux (Arch), Installed ssdeep package

`CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true cargo build`

<details><summary>Stack Trace</summary>
<p>

```
Compiling libfuzzy-sys v0.2.0

Caused by:
  process didn't exit successfully: `/home/tangerine-dev/Documents/Programming/Rust/Aurora/target/debug/build/libfuzzy-sys-c071d6af6789541e/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  TARGET = Some("x86_64-unknown-linux-gnu")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  HOST = Some("x86_64-unknown-linux-gnu")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  DEBUG = Some("true")
  cargo:rustc-link-lib=static=fuzzy
  cargo:rustc-link-search=/home/tangerine-dev/Documents/Programming/Rust/Aurora/target/debug/build/libfuzzy-sys-767d15ccf6f3de7d/out/.libs
  INFO: running command: cd "/home/tangerine-dev/Documents/Programming/Rust/Aurora/target/debug/build/libfuzzy-sys-767d15ccf6f3de7d/out" && CFLAGS="-O0 -ffunction-sections -fdata-sections -fPIC -g -m64 -Wall -Wextra -fPIC" "sh" "/home/tangerine-dev/Documents/Programming/Rust/Aurora/\"$XDG_DATA_HOME\"/cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzy-sys-0.2.0/libfuzzy/configure" "--enable-shared=no" "--enable-static=yes"
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane...
  --- stderr
  configure: error: unsafe srcdir value: '/home/tangerine-dev/Documents/Programming/Rust/Aurora/"$XDG_DATA_HOME"/cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzy-sys-0.2.0/libfuzzy'
  thread 'main' panicked at /home/tangerine-dev/Documents/Programming/Rust/Aurora/"$XDG_DATA_HOME"/cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzy-sys-0.2.0/build.rs:76:5:
  FAIL: command did not execute successfully: exit status: 1

  build script failed
```

</p>
</details>

**Comment by Eclextic** [comment]
So it works with `sudo`...
But why the hell should I use `sudo` to build a project?

But trying it out through `sudo` and you got an underrated project in here!
Thanks!

**Comment by Eclextic** [comment]
Also here is the normal build process:

<details><summary>Details</summary>
<p>

Command: `cargo build`

```
Caused by:
  process didn't exit successfully: `/home/tangerine-dev/Documents/Programming/Rust/Aurora/target/debug/build/libfuzzy-sys-6898227aae94494f/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  TARGET = Some("x86_64-unknown-linux-gnu")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  HOST = Some("x86_64-unknown-linux-gnu")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  DEBUG = Some("true")
  cargo:rustc-link-lib=static=fuzzy
  cargo:rustc-link-search=/home/tangerine-dev/Documents/Programming/Rust/Aurora/target/debug/build/libfuzzy-sys-32006ca00427ed24/out/.libs
  INFO: running command: cd "/home/tangerine-dev/Documents/Programming/Rust/Aurora/target/debug/build/libfuzzy-sys-32006ca00427ed24/out" && CFLAGS="-O0 -ffunction-sections -fdata-sections -fPIC -g -m64 -Wall -Wextra -fPIC" "sh" "/home/tangerine-dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzy-sys-0.2.0/libfuzzy/configure" "--enable-shared=no" "--enable-static=yes"
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether make supports nested variables... yes
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking for style of include used by make... GNU
  checking dependency style of gcc... gcc3
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking dependency style of g++... gcc3
  checking how to print strings... printf
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... dlltool
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /usr/bin/dd
  checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
  checking for mt... no
  checking if : is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... no
  checking whether to build static libraries... yes
  checking how to run the C++ preprocessor... g++ -E
  checking for ld used by g++... /usr/bin/ld -m elf_x86_64
  checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
  checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking for g++ option to produce PIC... -fPIC -DPIC
  checking if g++ PIC flag -fPIC -DPIC works... yes
  checking if g++ static flag -static works... yes
  checking if g++ supports -c -o file.o... yes
  checking if g++ supports -c -o file.o... (cached) yes
  checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking dynamic linker characteristics... (cached) GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking for /usr/local/include... yes
  checking for /usr/local/lib... yes
  checking for /opt/local/include... no
  checking for /opt/local/lib... no
  checking for /sw/include... no
  checking for /sw/lib... no
  checking whether byte ordering is bigendian... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking libgen.h usability... yes
  checking libgen.h presence... yes
  checking for libgen.h... yes
  checking dirent.h usability... yes
  checking dirent.h presence... yes
  checking for dirent.h... yes
  checking for inttypes.h... (cached) yes
  checking fcntl.h usability... yes
  checking fcntl.h presence... yes
  checking for fcntl.h... yes
  checking for sys/types.h... (cached) yes
  checking sys/ioctl.h usability... yes
  checking sys/ioctl.h presence... yes
  checking for sys/ioctl.h... yes
  checking sys/param.h usability... yes
  checking sys/param.h presence... yes
  checking for sys/param.h... yes
  checking wchar.h usability... yes
  checking wchar.h presence... yes
  checking for wchar.h... yes
  checking for unistd.h... (cached) yes
  checking for sys/stat.h... (cached) yes
  checking sys/disk.h usability... no
  checking sys/disk.h presence... no
  checking for sys/disk.h... no
  checking for inttypes.h... (cached) yes
  checking for sys/mount.h... yes
  checking for _LARGEFILE_SOURCE value needed for large files... no
  checking that generated files are newer than configure... done
  configure: creating ./config.status

  --- stderr
  chmod: changing permissions of './config.status': Operation not permitted
  configure: error: write failure creating ./config.status
  thread 'main' panicked at /home/tangerine-dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzy-sys-0.2.0/build.rs:76:5:
  FAIL: command did not execute successfully: exit status: 1
```

</p>
</details>

**Comment by s3rvac** [comment]
Hi, thank you for the report. Although I was unable to directly reproduce the issue on my Arch Linux installation, I have released a [new version of the package](https://github.com/s3rvac/ssdeep-rs/releases/tag/0.4.0) (`0.4.0`) that contains several improvements/fixes. Could you please try it and let me know if it fixes the issue for you?

**Comment by Eclextic** [comment]
Now it works! Thank you very much! Been having a blast using this library!
Gonna close this now.

<details><summary>Quick question... If you have the time</summary>
<p>

I know the ssdeep algorithm should only be used with large buffers/text files, but is there a way to make it work with smaller ones? Should I use a factor to determine how high the percentage of the comparison should be in accordance to the files size? Any pitfalls with this approach?

</p>
</details>

**Comment by s3rvac** [comment]
> Now it works! Thank you very much!

Great, thanks for the confirmation :+1:.

> I know the ssdeep algorithm should only be used with large buffers/text files, but is there a way to make it work with smaller ones? Should I use a factor to determine how high the percentage of the comparison should be in accordance to the files size? Any pitfalls with this approach?

I am afraid that I cannot help you here as this is rather a general question concerning ssdeep, which would perhaps be better suited to be asked in [its GitHub project](https://github.com/ssdeep-project/ssdeep).
